[tools]
dbmate = "2"
go = "1.25"
golangci-lint = "2"

[env]
DATABASE_URL = "postgres://postgres:password@localhost:5432/gokabot_db?sslmode=disable"
LOG_LEVEL = "DEBUG"

[vars]
dc = "docker compose -f docker-compose.local.yml"
go_api_dir = "gokabot-api-go"

[tasks.pull]
run = "{{vars.dc}} pull postgres hurl"
alias = "pl"

[tasks.build]
run = "{{vars.dc}} build"
alias = "bd"

[tasks.dev]
run = "{{vars.dc}} up"

[tasks.up-db]
run = "{{vars.dc}} up postgres"

[tasks.up-db-d]
run = "{{vars.dc}} up -d --wait postgres"

[tasks.up-api]
run = "{{vars.dc}} up gokabot-core-local"

[tasks.up-api-d]
run = "{{vars.dc}} up -d --wait gokabot-core-local"

[tasks.down]
run = "{{vars.dc}} down"

[tasks.db-migrate-new]
run = "dbmate new"
alias = "dm-new"

[tasks.db-migrate]
run = "dbmate migrate"
alias = "dm"

[tasks.db-migrate-rollback]
run = "dbmate rollback"
alias = "dm-rb"

[tasks.db-migrate-status]
run = "dbmate status"
alias = "dm-st"

[tasks.psql]
run = "{{vars.dc}} exec postgres psql $DATABASE_URL"

[tasks.db-seed]
run = "{{vars.dc}} exec -T postgres psql $DATABASE_URL < db/seeds/development.sql"
alias = "dm-sd"

[tasks.db-seed-test]
run = "{{vars.dc}} exec -T postgres psql $DATABASE_URL < db/seeds/test.sql"
alias = "dm-sd-t"

[tasks.test-api]
run = [
  { task = "db-migrate" },
  { task = "db-seed-test" },
  "{{vars.dc}} run --rm hurl",
]
alias = "ta"

[tasks.go-build]
run = "go build -o bin/gokabot-api ./cmd/gokabot/main.go"
alias = "gb"
dir = "{{vars.go_api_dir}}"

[tasks.go-run]
run = "go run ./cmd/gokabot/main.go"
alias = "gr"
dir = "{{vars.go_api_dir}}"

[tasks.go-lint]
run = "golangci-lint run ./..."
alias = "gl"
dir = "{{vars.go_api_dir}}"

[tasks.go-test]
run = "go test -v ./..."
alias = "gt"
dir = "{{vars.go_api_dir}}"

[tasks.go-clean]
run = "go clean && rm -f bin/gokabot-api"
alias = "gc"
dir = "{{vars.go_api_dir}}"
