[tools]
dbmate = "2"

[env]
DATABASE_URL = "postgres://postgres:password@localhost:5432/gokabot_db?sslmode=disable"

[vars]
dc = "docker compose -f docker-compose.local.yml"

[tasks.dev]
run = "{{vars.dc}} up"

[tasks.up-db]
run = "{{vars.dc}} up postgres"

[tasks.down]
run = "{{vars.dc}} down"

[tasks.db-migrate-new]
run = "dbmate new"
alias = "dm-new"

[tasks.db-migrate]
run = "dbmate migrate"
alias = "dm"

[tasks.db-migrate-rollback]
run = "dbmate rollback"
alias = "dm-rb"

[tasks.db-migrate-status]
run = "dbmate status"
alias = "dm-st"

[tasks.psql]
run = "{{vars.dc}} exec postgres psql $DATABASE_URL"

[tasks.db-seed]
run = "{{vars.dc}} exec -T postgres psql $DATABASE_URL < db/seeds/development.sql"
alias = "dm-sd"

[tasks.db-seed-test]
run = "{{vars.dc}} exec -T postgres psql $DATABASE_URL < db/seeds/test.sql"
alias = "dm-sd-t"

[tasks.test-api]
run = [
  { task = "db-migrate" },
  { task = "db-seed-test" },
  "{{vars.dc}} run --rm hurl",
]
alias = "ta"
