branches:
  only:
    - master
    - develop

sudo: false

language: ruby

rvm:
  - 2.7.6

cache:
  - bundler
  - directories:
      - $HOME/.rvm

env:
  global:
    - secure: ZKrKANuYoB6ppci97D+hDzSfiBtLxsoWbx7JBrFK81RHxLyWcDI5qfJpPWUsFjxlSJRCTH7+uyHk7SSZWpSMEZuXPr1nl9ohAPK1S9EeFj7xGKXimmiu6a30jkmHrGmJwjJYWKiNvVfixtEuhbRMrSYwnwIfkjiTKWQ+fekyd6r8qpyyRTTa14tfDA9R41/AJDf7fAVD3PrAybf3ogWVIGWCSaj14dd+Ns9iA/lDmAwWCo9D0JIOlw9EVMDV7mefaofwmL6RYCsMhw+I7GtQPIOOR9R3xxqOnsdVataq3wJ74e5HqXoPvlt/jVGAFlWFahq/dpkOiDF4Q1ogxObFaGG3gjKLdJqnN2q5POOOLDGz6pxt5WSSQczzdyS/MOeIZn3ZmTI1EOe7tq3Iibyuun2pjvMEOtuOCfR7ZC5Sz86JfgqQ+1IdU8AFPq1XG8brXS8BGzfHpFGvh42yNMwTHlJCt8c2oe3ls7rjmyB/NMQPiU3+qv0j44anWL+gzqSWxboRQkBMpSMPA9S+gXX2wORNOmGvsoWMhDyM/e7f1pnYW+LfWqURQEwNi2roA8UH3NVNsBtPVVRWrmZLbWhjzGQQLGOPQKykAAg3vA3S1Ct/5hw+8/85OqlYJBsAclxftSC49WqPMSaZXM8CaiqWdBvMHpFyD5ao2mrhvLEa4R4=
    - secure: HX0MHucy2iHt6+e+O3zmAn7Q3/9azPmcIcvLYz0VwY6X8z8nL5lwJeUaoi8XwthjQLkU+rAAI3rUSn5rg/Di0Vuvns2vZnmqcltat2jJUZq4V3qK2UxAB/sJrnHEMW51bgsFP/N+6awcN98IPZMr+JANlLu7y+EYTtdPVnfXRT6nFbAUsT+cgEiFzdfoaXl6VyhbLefJNo503Carj2fk48cZdpxjzImXOZSWeBgMzk3+4Bx7doqigDQU7t9nSGPSH6rNfItKziNu4TZzDU/III2wSfEOpWiTIaV5W8Nm6F13/S+WnYYv4nTpHVIp46vPXx5txReqMupmULv5zG7RLofUJSbrf9PPHydduVu23/dS2Lhuhsso15qJpdnHjjg2T79l/MfS1jIpFFa2TFuVUfpGPQvNPzraLoXJs2KxWZ4xO1JEystWqJNHJxnXyR42vXRAh6GpiXxlPStRUazFtQ6YD5v+VdKE6z3sITKjXLcVmLGJg/QHQfTnhpJkeAnQmQpreh88Mwvd9m0VgN2SjOG3skodT4uzTpwNzR6t173sz71xyRGUhK5B/7eFjyReansCUpz71nbz88ytxh2cvkh/ikr86pwr2w/qkgFFHTO+ZVOqlG8PL3r4h5mzRVzFtpSLahtea8dRYh+WD6Que17+Dv1gHOxNDdeVUaTeMlQ=
    - secure: QLxRQsX9GGsDpT9ZauW0CqCRNqdgiJhGLlCgzVqDz2/3DoYDqaIfiEXgTjBTAvaK6bBGVomRwGA0D4B5dcBB1lk+z3Lbu62DQNAngTcKprvCdOArfXMJ3t8AKib/MwmNBrXmhAby/IKCLgYRhRcUShj5Cbs7qOZc0MhJD4ewYoi+9t5Sp3lquGIN1TRp9PbnGuGMH9rnJm0L1McUArAY3HneaFNTLKgYhT+DDpoYh3rhxuXWTlrhyBupIe7q1z/KQg0v9GFnWHtlFJtNTIC6JLvMBpR2QuCsmNbbigyJTJ0t6C10ZCChuetR0eVyA8pU2A5Z7BotzVk1yng60cuiTBmcGqYkm2Orft52cOCuyd5qbdSK55n3vHAWxV5Zz/vJBmQbblh6k6bECSFIjqMx44TRsiBwoEX3s8sqLI/5yW7oywvXxmWN/ndLFOaD6CHTNZ542YXyityNPRd3H2tK2l1OZV0VQhi7mKkMoqJ+yg8VTHusZahzKdlcwJeUgcLwt/Z7yW5WJGnQcKIOkVxMY4EC9PtWuRSBgerdJFbj/cOMC4Nx/kHNXdfP/r1y3OhrjTry3qljq/JEB6BJ1bjaOISkQvPx5pfH21lyqrEqgX63NSO8yB8aB2wQXSM/1Y7M85l1LfgUGxaa+Y8LrFuU+yoCz6Fgb3DASR2bYtbDHj8=
    - secure: QHfiS1SlN4xFUHJTtrpPCavMaOyuW7EiN+5QXy6n1dU5ikBuGwA2Qe2OzTDnENZdZQyoUCTUKHHxsQ65TgdS0f/CIZiYinTjEjPcAwpiyS6WfyPvXTNSVWKc0A0FVCFYnhM6cpgKirCvM0FDOMhhGiwZx/6JwBBdHSe2nbrteSl94lENdYhwktkQ0WJC5M2OjcDxW+tRHQjpPlqVVe3fP8akKFkYXAoDAjyHOqXvNOgd9n87/N0uAbJugbxYzzfXVRuDE97ZpJaYaB2vJuMQNd8gWJlxETeZJtASMiBREUzhphzSWz09yCKgGl5XKgn5uFeH1gTxFYvq/VpHjNEH+53Q9pmURA1Oqwk36BfI3juCQXGECz1epi/c1I2kDuaBgiovoJ7FHBwz7f9zhBulcXiuJ3OoDg6BrG9Bcg8nV232SV0GWpfCtNWHEKGDO+xRGWXISyIxB1SRbQ1INju5+3NL7D7+NtgZTeyiL/vc6sTnwD3H2ZE26p6uKn5PYcrK6kGc+LRvQoDOIk6hXGoh3wiI1sl5/uJiYXITii5qlUN3m+xKD2r7aTv2R2nWVEZjyXlVWZuKT7/GnC8/a29D+WlVdd2Crb7CyHidPRN/vlYykQZMKpSr4TyYj9c90hIYn7jDxcx1WxA2nHVRd8nacbRxQB2/pbSXyR+0NAxfGJA=
    - secure: ICwqbosDDgr7jbwZvXd1a6c0ZHO80oGUvfmSFlwpqNywfyO5O3Lg2Q/BCakT1xskJGZeB8YLrXDswSHX5M/BLSuZ/zAHrYFuRlYB840PRMRzDQwszxeqfDdIdCvRr9HRg9ZcNguQz5coMRTFpAVgK3sQ5H44KXG8PhVb2hHhvU66wATBZGKuoeAjJ94TpwZh9fZXvpSbLzqXyE9ZAGzeK9k4giH0jA5BO8MtK54oFUglmm2Y1G7b74vIyGn8sI2JNECuflsPaY0f6YLFoLPA0ZuJ9fOlZIUJMuM1WtRFDEFundndHRNkoGTJAN71NcnVEaXd9bwKBvrQzvUNVKNzFQVAArEUU1jR4iQSyPsxV8f1KlNhdQ7kxlwQs2q9FY1ON3yW7bMe5D6QOdPdQIRtx4xGo1EbmhBmeKVwctKEJ4PBxi1j3w/ClV9Eg3dGGpyc2orVyzjS5mP09H0uvXGX2bZp2uoPYpCjOFS7ba7f/HKwHp3dH6bo62qb8OSgN1a+NI4i9EQ1sCtrvBQ/5H12ucX1CXQOSapS1XOjVlNW4xMp4EwkZjUuVmyZaG45PlxYiO6MLHuiMf7a+Ff3h+BJVBQ3a/iJeK8x2jx+jm9JXuix2nDk3xRr5FhAFI/oDARKikMwFDi1sRqSURQrluPINKPXSo8Gam2Oz07GjeRaWbA=

addons:
  apt:
    packages:
      - mecab
      - libmecab-dev
      - mecab-ipadic
      - mecab-ipadic-utf8

before_install:
  - cd core-api
  - gem install bundler -v 2.1.2
  - bundle install --without development

script:
  - bundle exec rspec
