version: "2.1"

services:
  gokabot-core-local:
    image: gokabot-core-local
    container_name: gokabot-core-local
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
      RACK_ENV: development
    env_file:
      - core-api/.env
    build:
      context: core-api
    ports:
      - "8080:8080"
    command:
      [
        "bundle",
        "exec",
        "rackup",
        "app/config.ru",
        "-o",
        "0.0.0.0",
        "-p",
        "8080",
      ]

  gokabot-demo:
    image: gokabot-demo
    container_name: gokabot-demo
    environment:
      TZ: Asia/Tokyo
    build:
      context: gokabot-demo
    ports:
      - "3000:3000"
    command: ["yarn", "vite"]

  metabase:
    # see: https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html
    image: metabase/metabase
    container_name: gokabot-metabase
    volumes:
      - ~/.metabase:/metabase-data
    environment:
      TZ: Asia/Tokyo
      MB_DB_FILE: /metabase-data/metabase.db
    ports:
      - "5000:3000"
