version: '2.1'

services:
  gokabot-line:
    image: gokabot-line
    container_name: gokabot-line
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    build: .
    ports:
      - "8080:8080"
    command: [
      "bundle", "exec", "rackup", "app/config.ru",
      "-o", "0.0.0.0",
      "-p", "8080"
    ]
    