version: '2.1'

services:
  gokabot-line-local:
    image: gokabot-line-local
    container_name: gokabot-line-local
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    build: .
    ports:
      - "8081:8080"
    command: [
      "bundle", "exec", "rackup", "app-dev/config.ru",
      "-o", "0.0.0.0",
      "-p", "8080"
    ]
    restart: always
