version: "2.1"

services:
  gokabot-core:
    image: 678084882233.dkr.ecr.ap-northeast-1.amazonaws.com/gokabot-core:latest
    container_name: gokabot-core
    environment:
      TZ: Asia/Tokyo
    ports:
      - "8080:8080"
    env_file:
      - core-api/.env
    command:
      [
        "bundle",
        "exec",
        "rackup",
        "app/config.ru",
        "-o",
        "0.0.0.0",
        "-p",
        "8080",
      ]
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: gokabot
        awslogs-stream-prefix: gokabot-core
