version: '2.1'

services:
  gokabot-line:
    image: gokabot-line
    container_name: gokabot-line
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    build: .
    ports:
      - "8080:8080"
    command: [
      "bundle", "exec", "rackup", "app/config.ru",
      "-o", "0.0.0.0",
      "-p", "8080"
    ]
    restart: always
    logging:
      driver: awslogs
      options: 
        awslogs-region: ap-northeast-1
        awslogs-group: docker-logs
        awslogs-create-group: "true"
        awslogs-stream: gokabot-line
