version: "2.1"

services:
  gokabot-line-dev:
    image: gokabot-line-dev
    container_name: gokabot-line-dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    build: .
    ports:
      - "8081:8080"
    command:
      [
        "bundle",
        "exec",
        "rackup",
        "app-dev/config.ru",
        "-o",
        "0.0.0.0",
        "-p",
        "8080",
      ]
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: docker-logs
        awslogs-create-group: "true"
        awslogs-stream: gokabot-line-dev
