source 'https://rubygems.org'

ruby '2.7.4'

gem 'activerecord'
gem 'discordrb'
gem 'dotenv'
gem 'faraday'
gem 'line-bot-api'
gem 'mechanize'
gem 'natto'
gem 'nokogiri'
gem 'pg'
gem 'puma'
gem 'puma_worker_killer'
gem 'rexml'
gem 'sinatra'
gem 'sinatra-cors'
gem 'zen_to_i'

group :test do
  gem 'rspec'
end

group :development do
  gem 'debase'
  gem 'pry'
  gem 'rubocop'
  gem 'ruby-debug-ide'
  gem 'solargraph'
end
