source 'https://rubygems.org'

ruby '2.6.6'

gem 'activerecord'
gem 'discordrb'
gem 'dotenv'
gem 'line-bot-api'
gem 'mechanize'
gem 'natto'
gem 'nokogiri'
gem 'pg'
gem 'rest-client'
gem 'rexml'
gem 'sinatra'
gem 'sinatra-cors'
gem 'zen_to_i', '0.0.2'

group :test do
  gem 'rspec'
end

group :development do
  gem 'debase'
  gem 'pry'
  gem 'rubocop'
  gem 'ruby-debug-ide'
  gem 'solargraph'
end
