root = "."
tmp_dir = "tmp"

[build]
cmd = "golangci-lint run ./... && go test ./... && go build -o ./tmp/gokabot-api ./cmd/gokabot/main.go"
bin = "./tmp/gokabot-api"
include_ext = ["go"]
include_file = ["go.mod", "go.sum"]
exclude_dir = ["tmp", "bin"]
delay = 1000

[log]
time = true

[misc]
clean_on_exit = true
