FROM golang:1.25-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

COPY . .
RUN go build -o /gokabot-api ./cmd/gokabot

EXPOSE 8081

ENTRYPOINT ["/gokabot-api"]
