name: Check API

on:
  push:
    branches:
      - main
    paths:
      - "gokabot-api-go/**"
      - ".github/workflows/check-api.yml"
  pull_request:
    paths:
      - "gokabot-api-go/**"
      - ".github/workflows/check-api.yml"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install_args: "go golangci-lint"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: mise go-lint

      - name: Unit test
        run: mise go-test

      - name: Build
        run: mise go-build
