name: Dependabot Auto Approve and Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Dependabot Auto Approve and Merge
        uses: 23prime/simple-dependabot-auto-approve-and-merge@1f3c00f396e7b680c81e3503aa6ecd3bef811cd6 # v1.0.0
        with:
          pr-url: ${{ github.event.pull_request.html_url }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
